# Generated by Django 5.2.4 on 2025-08-03 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0002_employee_employee_number_employee_first_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employee",
            options={"ordering": ["last_name", "first_name"]},
        ),
    ]
