# Generated by Django 5.0.14 on 2025-08-09 19:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0003_alter_employee_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employee",
            options={
                "ordering": ["last_name", "first_name"],
                "verbose_name": "Employee",
                "verbose_name_plural": "Employees",
            },
        ),
        migrations.AlterField(
            model_name="employee",
            name="department",
            field=models.CharField(
                help_text="Department or work area assignment", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="email",
            field=models.EmailField(
                help_text="Corporate email address", max_length=254
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="employee_id",
            field=models.CharField(help_text="Legacy employee ID field", max_length=20),
        ),
        migrations.AlterField(
            model_name="employee",
            name="employee_number",
            field=models.CharField(
                default="",
                help_text="Unique employee number in format EMP-XXX",
                max_length=20,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_employee_number",
                        message="Employee number must be in format EMP-XXX (e.g., EMP-001)",
                        regex="^EMP-\\d{3}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="first_name",
            field=models.CharField(
                default="", help_text="Employee first name", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="last_name",
            field=models.CharField(
                default="", help_text="Employee last name", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="name",
            field=models.CharField(
                help_text="Full name (legacy field)", max_length=100
            ),
        ),
    ]
