# Generated by Django 5.2.4 on 2025-07-24 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workcenters', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workcenter',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='workcenter',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='workcenter',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
