# Generated by Django 5.2.4 on 2025-08-03 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workcenters", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workcenter",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
