# Generated by Django 5.2.4 on 2025-08-03 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workcenters", "0002_workcenter_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="workcenter",
            options={"ordering": ["name"]},
        ),
    ]
