# Generated by Django 5.0.14 on 2025-08-09 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workcenters", "0003_alter_workcenter_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="workcenter",
            options={
                "ordering": ["name"],
                "verbose_name": "Work Center",
                "verbose_name_plural": "Work Centers",
            },
        ),
        migrations.AlterField(
            model_name="workcenter",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Detailed description of work center operations and capabilities",
            ),
        ),
        migrations.AlterField(
            model_name="workcenter",
            name="location",
            field=models.CharField(
                help_text="Physical location (building, floor, bay)", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="workcenter",
            name="name",
            field=models.CharField(
                help_text="Work center identifier or code", max_length=100, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="workcenter",
            name="supervisor",
            field=models.CharField(
                help_text="Work center supervisor name", max_length=100
            ),
        ),
    ]
