# Generated by Django 5.0.14 on 2025-08-13 16:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("employees", "0004_alter_employee_options_alter_employee_department_and_more"),
        ("tools", "0004_alter_tool_options_alter_tool_calibrated_and_more"),
        ("workcenters", "0004_alter_workcenter_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ToolMeasure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "measurement_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Date and time measurement was performed",
                    ),
                ),
                (
                    "size_measured",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Measured size/dimension",
                        max_digits=10,
                    ),
                ),
                (
                    "expected_size",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Expected/nominal size",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "tolerance",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Acceptable tolerance",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("GOOD", "Good"),
                            ("FAIR", "Fair"),
                            ("POOR", "Poor"),
                            ("NEEDS_REPAIR", "Needs Repair"),
                        ],
                        default="GOOD",
                        help_text="Overall tool condition",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about the measurement"
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        help_text="Employee performing the measurement",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employees.employee",
                    ),
                ),
                (
                    "tool",
                    models.ForeignKey(
                        help_text="Tool being measured",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tools.tool",
                    ),
                ),
                (
                    "work_center",
                    models.ForeignKey(
                        blank=True,
                        help_text="Work center where measurement was performed",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="workcenters.workcenter",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tool Measure",
                "verbose_name_plural": "Tool Measures",
                "ordering": ["-measurement_date"],
            },
        ),
    ]
