# Generated by Django 5.0.14 on 2025-08-13 16:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("employees", "0004_alter_employee_options_alter_employee_department_and_more"),
        ("tools", "0004_alter_tool_options_alter_tool_calibrated_and_more"),
        ("workcenters", "0004_alter_workcenter_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ToolTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "checkout_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Date and time tool was checked out",
                    ),
                ),
                (
                    "promise_return_date",
                    models.DateField(
                        blank=True, help_text="Promised return date", null=True
                    ),
                ),
                (
                    "return_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date and time tool was returned",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CHECKED_OUT", "Checked Out"),
                            ("RETURNED", "Returned"),
                        ],
                        default="CHECKED_OUT",
                        help_text="Current status of the transaction",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about the transaction"
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        help_text="Employee checking out/returning the tool",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employees.employee",
                    ),
                ),
                (
                    "from_location",
                    models.ForeignKey(
                        blank=True,
                        help_text="Work center tool is being taken from",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="outgoing_transactions",
                        to="workcenters.workcenter",
                    ),
                ),
                (
                    "return_employee",
                    models.ForeignKey(
                        blank=True,
                        help_text="Employee who processed the return",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="returned_transactions",
                        to="employees.employee",
                    ),
                ),
                (
                    "to_location",
                    models.ForeignKey(
                        blank=True,
                        help_text="Work center tool is being taken to",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incoming_transactions",
                        to="workcenters.workcenter",
                    ),
                ),
                (
                    "tool",
                    models.ForeignKey(
                        help_text="Tool being checked out/returned",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tools.tool",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tool Transaction",
                "verbose_name_plural": "Tool Transactions",
                "ordering": ["-checkout_date"],
            },
        ),
    ]
