# Generated by Django 5.2.4 on 2025-07-07 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=50)),
                ('calibrated', models.BooleanField(default=False)),
                ('last_checked_in', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
