# Generated by Django 5.2.4 on 2025-07-24 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employee_options_employee_hire_date_and_more'),
        ('tools', '0001_initial'),
        ('workcenters', '0002_alter_workcenter_options_workcenter_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tools', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='tool',
            name='checked_out_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='current_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tools', to='workcenters.workcenter'),
        ),
        migrations.AddField(
            model_name='tool',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('checked_out', 'Checked Out'), ('maintenance', 'In Maintenance'), ('calibration', 'In Calibration')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='tool',
            name='serial_number',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
