# Generated by Django 5.2.4 on 2025-08-03 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0001_initial"),
        ("workcenters", "0002_workcenter_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="tool",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="tool",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="workcenters.workcenter",
            ),
        ),
    ]
