# Generated by Django 5.2.4 on 2025-08-03 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0002_tool_description_tool_location"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tool",
            options={"ordering": ["name"]},
        ),
    ]
