# Generated by Django 5.0.14 on 2025-08-09 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0003_alter_tool_options"),
        ("workcenters", "0004_alter_workcenter_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tool",
            options={
                "ordering": ["name"],
                "verbose_name": "Tool",
                "verbose_name_plural": "Tools",
            },
        ),
        migrations.AlterField(
            model_name="tool",
            name="calibrated",
            field=models.BooleanField(
                default=False, help_text="Current calibration status"
            ),
        ),
        migrations.AlterField(
            model_name="tool",
            name="description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Detailed tool description and specifications",
            ),
        ),
        migrations.AlterField(
            model_name="tool",
            name="last_checked_in",
            field=models.DateTimeField(
                blank=True, help_text="Last time tool was checked in/used", null=True
            ),
        ),
        migrations.AlterField(
            model_name="tool",
            name="location",
            field=models.ForeignKey(
                blank=True,
                help_text="Current work center assignment",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="workcenters.workcenter",
            ),
        ),
        migrations.AlterField(
            model_name="tool",
            name="name",
            field=models.CharField(
                help_text="Tool name or model designation", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="tool",
            name="serial_number",
            field=models.CharField(
                help_text="Unique serial number or identifier",
                max_length=50,
                unique=True,
            ),
        ),
    ]
